runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10  # Adjust this value to be within the allowed limit

env_variables:
  PLAYWRIGHT_BROWSERS_PATH: 'D:/anaconda/Scripts'

handlers:
- url: /.*
  script: auto
